# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=80)),
                ('coach_middle_name', models.CharField(max_length=80)),
                ('coach_surname', models.CharField(max_length=80)),
                ('coach_year_birth', models.DateField(default=django.utils.datetime_safe.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=80)),
                ('player_middle_name', models.CharField(max_length=80)),
                ('player_surname', models.CharField(max_length=80)),
                ('player_year_birth', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('player_photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=80)),
                ('team_created_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('team_text', models.TextField()),
                ('team_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Coach')),
                ('team_emblem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Photo'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Rank'),
        ),
    ]
